### ISSUE TITLE
AX_COMPILER_FLAGS_CFLAGS error

### ISSUE THREAD

**Issue by expenses** [talisein/mal-gtk#2]
Tried compiling on Arch. While running ./autogen.sh I ran into the following error:

```
./configure: line 4596: syntax error near unexpected token `AX_COMPILER_FLAGS_CFLAGS'
./configure: line 4596: `               AX_REQUIRE_DEFINED(AX_COMPILER_FLAGS_CFLAGS)
```

**Comment by talisein** [comment]
Should be fixed with commit 8d934e. If not let me know.

**Comment by expenses** [comment]
Now `./autogen.sh` and `make -j8` run fine, but now running `src/mal-gtk` or `mal-gtk` after installing returns:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
zsh: abort (core dumped)  src/mal-gtk
```

**Comment by talisein** [comment]
Ah.. I think this exception is from test_util.cpp, and I think it is written like this because libstdc++ didn't get the codecvt header until gcc 5.1. I'll work on this.

**Comment by talisein** [comment]
Done in 3c3744
